stages:
  - lint
  - build
  - test
  - deploy


eslint-job:
  stage: lint
  image: node:latest
  script:
    - npm install
    - npm run lint
  only:
    - project
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

docker-build:
  
  stage: build
  image: docker:latest
  services:
    - name: docker:19.03.12-dind  # Docker-in-Docker service
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375  # Configure Docker CLI to use Docker-in-Docker
    DOCKER_DRIVER: overlay2
  script:
    - echo "Building and starting services with Docker Compose"
    #- docker ps -a
    
    # Remove all containers 
    #- docker rm -f backend3-1
    #- docker rm -f backend2-1
    #- docker rm -f backend1-1
    #- docker rm -f service2
    #- docker rm -f nginx_frontend
    #- docker rm -f redis
    - docker compose up --build -d  # Use -d to run detached

test-job:
  stage: test
  script:
    - echo "Running tests with services up"
    - npm install
    - npm test

deploy-prod:
  stage: deploy
  script:
    - echo "Deploying to production"
    - docker compose down  # Optional: Clean up services after deployment
  environment: production
