build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

docker-build:
  stage: build
  script:
    - echo "Building and starting services with Docker Compose"
    - docker ps -a
    - docker rm -f backend3-1
    - docker rm -f backend2-1
    - docker rm -f backend1-1
    - docker rm -f service2
    - docker rm -f nginx_frontend
    - docker-compose up --build -d  # Use -d to run detached

test-job1:
  stage: test
  script:
    - echo "Running tests with services up"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - sleep 20  # Simulating a longer-running test

deploy-prod:
  stage: deploy
  script:
    - echo "Deploying to production"
    - docker-compose down  # Optional: Clean up services after deployment
  environment: production
