services:
  
  service1:
    image: service1:latest
    command: sh -c "npm install && npm start"
    build:
      dockerfile: Docker1
      context:  ./service1/
    # Only service1 accessible from outside
    ports:
      - "8199:8199"
    networks:
      - backend

  service2:
    image: service2:latest
    command: sh -c "mvn package && java -cp target/service2-1.0-SNAPSHOT.jar service2.App"
    build:
      dockerfile: Docker2
      context:  ./service2/
    expose:
      - 8200
    networks:
      - backend
    # Connect both to backend
networks:
  backend: