concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-runner"
  url = "https://compse140.devops-gitlab.rd.tuni.fi"
  id = 237
  token = "glrt-t3_jxoCs86_DyknxZynrSWN"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "docker:24.0.2"
    privileged = true