services:
  

  gitlab-runner:
    image: gitlab/gitlab-runner:latest # Official GitLab Runner image
    container_name: gitlab_runner
    restart: always # Automatically restart if the container stops
    volumes:
      - ./config:/etc/gitlab-runner # Store GitLab Runner configuration persistently
      - /var/run/docker.sock:/var/run/docker.sock # Enable Docker-in-Docker for building images
    environment:
      - RUNNER_NAME=gitlab-runner
      - CI_SERVER_URL=https://compse140.devops-gitlab.rd.tuni.fi # Replace with your GitLab instance URL
      - REGISTER_NON_INTERACTIVE=true
