services:
  
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always # Automatically restart if the container stops
    volumes:
      - ./config:/etc/gitlab-runner # Store GitLab Runner configuration persistently
      - /var/run/docker.sock:/var/run/docker.sock # Enable Docker-in-Docker for building images
    environment:
      - RUNNER_NAME=gitlab-runner
      - CI_SERVER_URL=https://compse140.devops-gitlab.rd.tuni.fi 
      - REGISTER_NON_INTERACTIVE=true
