concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800


[[runners]]
  name = "gitlab-runner"
  url = "https://compse140.devops-gitlab.rd.tuni.fi"
  id = 106
  token = "glrt-t3_LrCbzqsJ_Uqj4F_NsDyr"
  token_obtained_at = 2025-01-21T08:02:01Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
