concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "devops"
  url = "https://compse140.devops-gitlab.rd.tuni.fi"
  id = 0
  token = "GR13489417YuPiSc5HHvDdsDcdxyo"
  token_obtained_at = 0001-01-01T00:00:00Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  shell = "bash"
  pre_build_script = "source ~/.bashrc"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "gitlab-docker-runner"
  url = "https://compse140.devops-gitlab.rd.tuni.fi"
  id = 106
  token = "glrt-t3_LrCbzqsJ_Uqj4F_NsDyr"
  token_obtained_at = 2025-01-21T08:02:01Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
